# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
 build:
   docker:
     - image: mcr.microsoft.com/dotnet/sdk:5.0
   steps:
     - checkout
     - run:
         name: Restore packages
         command:
           dotnet restore
     - run:
         name: Build App
         command:
           dotnet build
     - run:
         name: Test App
         command:
           dotnet test
